### ISSUE TITLE
Include Folder for whole Path?

### ISSUE THREAD

**Issue by irstmon** [willemdh/check_ms_win_tasks#13]
Hi,

Thanks for your script! I'm using it to monitor 2 machines and the script works great. However I would like to monitor a third machine - but only the tasks in a special folder (right below the \\ root). However it seems that -IF works as a wildcard and I cant get it to JUST report the specific folder. Stepts to reproduce (on Server 2016, I think other OS should have the same default foders under the Microsoft tree):

- Create a folder named App right below the root
- Place just 1 Task there and run it one time
- us -IF "APP"

I get 10 Tasks geported - because there are 9 Tasks under Microsoft\Windows\AppID and other folders that match App. Trying with \\APP and so on didn't get the 1 task to display. Maybe I don't see the right way to do this?

**Comment by willemdh** [comment]
Hmm it works like this:

```powershell
  ForEach ($folder in $TempValidFolders) {
    If (Compare-Array -Str $Folder.Name -Patterns $Struct.InclFolders){
      $Struct.AllValidFolders += $Folder	
    }
  }
```

```powershell
Function Compare-Array  {
  Param(
    [Parameter(Mandatory=$True,HelpMessage='String to search')][string]$Str,
    [Parameter(Mandatory=$True,HelpMessage='Array to search')][AllowEmptyCollection()][String[]]$Patterns
  )
  ForEach ( $Pattern in $Patterns ) { 
    If ( $Str -Match $Pattern ) {
      Return $True
    } 
  }
  Return $False
}
```

There are better options atm, but at the time I created this plugin, only powershell v2 was available. I'm a bit reluctant to change the way it works now, as it could potentially have an impact for people who want to match on all InclFolders values. The easiest way to make it work for you might be to make it a unique name, egg APP123?

**Comment by irstmon** [comment]
That's the way I've taken - but I wasn't sure if it's a bug or a feature ;-) (Or I'm using it wrong)

I can understand that changing the way might break it for a lot of other people. Since I've switched to unique folders I found a way to get it 'right'

**Comment by willemdh** [comment]
@irstmon Ok, I'm going to close this issue, as for now it's imho a feature :) (and I have no time to fix this)
