### ISSUE TITLE
is there a way to check if a task is enabled or not?

### ISSUE THREAD

**Issue by e0xify** [willemdh/check_ms_win_tasks#2]
just want to know if the task is enabled or disabled yet, if it gets disabled i want to recieve a critical.

any ideas?

**Comment by willemdh** [comment]
This is not something in the scope of this plugin. This is something that you should do with 
- NSClient real-time eventlog monitoring
- ELK stack

These are the Audit object access events needed:
4698 - A scheduled task was created. 
4699 - A scheduled task was deleted. 
4700 - A scheduled task was enabled. 
4701 - A scheduled task was disabled. 
4702 - A scheduled task was updated.

Closing this up.
