### ISSUE TITLE
Problem with Exitcode:1

### ISSUE THREAD

**Issue by Kervus** [willemdh/check_ms_win_tasks#3]
Thanks you very much for this, it’s really usefull for me and it’s helping me a lot.

In the other hand, I have a question, I’m having some false positives in tasks that never has started, showing that info, for example:

> ” {Taskname: “Copia Abril” (Author: DOMAIN\USER)(Exitcode: 1)(Last runtime: 12/30/1899 00:00:00)} {Taskname: “Copia Agost 17″ (Author: DOMAIN\USER)(Exitcode: 1)(Last runtime: 12/30/1899 00:00:00)}” ”

There are some option for ignore scheduled tasks that has never started? there are some tasks, that are started and ended correctly but it returns "Exitcode: 1", so, Nagios show me a fail:

> "1 / 2 tasks failed! {Taskname: "Copia Biostar" (Author: DOMAIN\USER)(Exitcode: 1)(Last runtime: 10/13/2016 07:00:00)}"

so, it's possible to admit the exit code: 1 in ok tasks?

**Comment by willemdh** [comment]
Not by default as some tasks exit 1 and are effectively failed. i'll think about adding an option.

**Comment by willemdh** [comment]
After discussing this internally, this just seems like a bad idea. You should have another look at your tasks and just make sure they exit properly (with exitcode 0)
