### ISSUE TITLE
Extend documentation "How to monitor your scheduled tasks?"

### ISSUE THREAD

**Issue by simon04** [willemdh/check_ms_win_tasks#5]
In https://outsideit.net/monitoring-windows-scheduled-tasks/, section "How to monitor your scheduled tasks?":

* Link "define the script like this" to https://docs.nsclient.org/tutorial/#external-scripts
* For item 2, add the INI section `[/settings/external scripts/scripts]` on top to guide the reader to the correct section
* Consider defining a wrapped script, see https://docs.nsclient.org/howto/external_scripts/#wrapped-scripts

**Comment by willemdh** [comment]
Updated documentation.
