### ISSUE TITLE
Alert wrong when instance is already running: 0x8004131F

### ISSUE THREAD

**Issue by nmat** [willemdh/check_ms_win_tasks#7]
The error: 0x8004131F is alerting all the time however it means that: "Launch request ignored, instance already running", the script entry below will fix this for that specific result:

```
<                 If ( $ObjTask.LastTaskResult -eq '0'-or $ObjTask.LastTaskResult -eq '0x00041325' -and $ObjTask.Enabled ) {

>                 If ( $ObjTask.LastTaskResult -eq '0x8004131F'-or $ObjTask.LastTaskResult -eq '0'-or $ObjTask.LastTaskResult -eq '0x00041325' -and $ObjTask.Enabled ) {
```

**Comment by willemdh** [comment]
Never had that error. Ideally it should be possible to exclude errors as a parameter.

**Comment by nmat** [comment]
Checking documentation:

https://msdn.microsoft.com/en-us/library/windows/desktop/aa383604(v=vs.85).aspx

SCHED_E_ALREADY_RUNNING
0x8004131F
An instance of this task is already running.

**Comment by nmat** [comment]
might be even more error numbers in there that can be applied to the rules set in the ps1 script to minimize the alerts of a running instance/task

**Comment by nmat** [comment]
`ElseIf ( $ObjTask.LastTaskResult -eq '0x8004131F'-or $ObjTask.LastTaskResult -eq '0x00041301' -and $ObjTask.Enabled ) {
            If ( ! $Struct.InclTasks ) {
                If ( ! ( Compare-Array -Str $ObjTask.Name -Patterns $Struct.ExclTasks ) ) {
                    $Struct.RunningTasks += $ObjTask
                    $Struct.TasksRunning += 1
                }
            }`

**Comment by nmat** [comment]
last one is more correct when following the documentation

**Comment by bsivavani** [comment]
Hi,

We are also facing the same issue, receiving CRITICAL alert even though task is running because of 0x8004131F Error code.

Modified the ps code as suggested to fix the issue.

**Comment by willemdh** [comment]
Integrated this in the last commit. Closing.
