### ISSUE TITLE
Assume 'success' for tasks that never ran (yet)

### ISSUE THREAD

**Issue by ngaullier** [willemdh/check_ms_win_tasks#8]
When a task was just created and was still never run, its 'LastRunTime' is set to a date far away in 1989 which means "never". Such task should be assumed "OK" ; its 'LastTaskResult' remains undefined I think.
Line 447, I would add :
-or $ObjTask.LastRunTime -lt (get-date 2000-01-01)
NB: I have not found any "clean" way to get the value of this '1989' date, so I use 2000 which seems reasonable but somewhat 'dirty'.
Thanks for your script
Nicolas

**Comment by willemdh** [comment]
Thanks for the suggestion. When I find some time I'll try to integrate it.

**Comment by willemdh** [comment]
Integrated this in the last commit. Closing.
